global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: prometheus
    static_configs:
      - targets: [ localhost:9090 ]

  - job_name: order-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 192.168.56.1:8081 ]
        labels:
          service: order-service
          team: backend

  - job_name: analytics-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 192.168.56.1:8093 ]
        labels:
          service: analytics-service
          team: backend
