server.port=8087
spring.application.name=user-service

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/user_db?options=-c%20TimeZone=UTC&sslmode=disable
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=http://${EUREKA_HOST:localhost}:8761/eureka/
eureka.instance.prefer-ip-address=true

ip-address: true



#POST http://localhost:8087/api/v1/users/profile
#
#{
#"fullName": "Jagdish Kumar",
#"email": "jagdish@example.com",
#"phoneNumber": "+91-9876543210"
#}



#GET http://localhost:8087/api/v1/users/profile



#PUT http://localhost:8087/api/v1/users/profile
#
#{
#"fullName": "Jagdish Kumar Sahu",
#"phoneNumber": "+91-9999999999"
#}



#PUT = replace/update the whole resource
#PATCH = partially update the resource



#DELETE http://localhost:8087/api/v1/users/profile
#
#Headers:
#X-User-Id: 11111111-1111-1111-1111-111111111111


#
#GET http://localhost:8087/api/v1/users/addresses
#Headers:
#X-User-Id: 11111111-1111-1111-1111-111111111111



#POST http://localhost:8087/api/v1/users/addresses
#Headers:
#X-User-Id: 11111111-1111-1111-1111-111111111111
#Content-Type: application/json
#
#Body:
#{
#"label": "Home",
#"recipientName": "Jagdish Kumar",
#"phoneNumber": "+91-9876543210",
#"addressLine1": "123 MG Road",
#"addressLine2": "Near City Mall",
#"city": "Bangalore",
#"state": "Karnataka",
#"postalCode": "560001",
#"country": "India",
#"defaultAddress": true
#}



#PUT http://localhost:8087/api/v1/users/addresses/{addressId}
#Headers:
#X-User-Id: 11111111-1111-1111-1111-111111111111
#Content-Type: application/json
#
#Body:
#{
#"label": "Office",
#"recipientName": "Jagdish Kumar",
#"phoneNumber": "+91-9876543210",
#"addressLine1": "456 Koramangala",
#"addressLine2": "Block 5",
#"city": "Bangalore",
#"state": "Karnataka",
#"postalCode": "560034",
#"country": "India",
#"defaultAddress": false
#}



#DELETE http://localhost:8087/api/v1/users/addresses/{addressId}
#Headers:
#X-User-Id: 11111111-1111-1111-1111-111111111111
#
#Response: 204 No Content


#
#PATCH http://localhost:8087/api/v1/users/addresses/{addressId}/default
#Headers:
#X-User-Id: 11111111-1111-1111-1111-111111111111
#
#Response: 200 ? updated address with defaultAddress: true

